### PR TITLE
Fix "New Function" Dialog (#3102)

### LINKED ISSUE #3102: "New Function" dialog: too short by default and Z-Order broken
**Environment information**

* Operating System: Windows 7 x64
* Cutter version: 2.1.2 release and 2.1.2-git-1211 https://github.com/rizinorg/cutter/commit/baeffba7d1b2f783c06cc3af51ba7533b3f6df15
* Obtained from: Downloaded release from Cutter website or GitHub

2023-02-02 06_05_37-Disassembly 1 (unsynced)

Granted, the window might be resized, but it is not immediately obvious.

2023-02-02 06_06_01-vthF6nA png (743×502) - Vivaldi

This one is somewhat annoying...

The underlying reason is that there is no Z-Order relationship set between Cutter windows, and they are all thrown into one same plane.

Then you employ the "always-on-top" window work-around, and end up floating over other applications too.

Correct behaviour should be removing the "always-on-top" flag and setting the "Disassenby 1" window as the parent for this new dialog, like other applications do to their windows.

2023-02-02 06_31_14-Window Detective

Not sure what should be the Qt5 API for it, but i think such a mature library should have one.

### PR DESCRIPTION
**Pull request by whol-hoopa**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

The "New Function" Dialog has been expanded
The main window gets minimized along with the dialog.
The dialog window doesn't stay on top when opening another window

**Test plan (required)**

1.Right click the disassembly then use the "New Function" on the menu

*Dialog Window overlapped window and the dialog title is cluttered together*
image

*Dialog Window is Larger*
image

*Dialog Window doesn't overlap other windows*
image

**Closing issues**

closes #3102

### CODE REVIEW

**Review by XVilka — APPROVED** [review]
Not sure if it's a good idea to hardcode the size. The rest is fine.

**Comment by wargio** [comment]
> Not sure if it's a good idea to hardcode the size. The rest is fine.

where is that?

File: src/menus/DisassemblyContextMenu.cpp [hunk 1]
```diff
@@ -812,12 +810,20 @@ void DisassemblyContextMenu::on_actionAnalyzeFunction_triggered()
     }
 
     // Create dialog
-    QString functionName =
-            QInputDialog::getText(this, tr("New function at %1").arg(RzAddressString(offset)),
-                                  tr("Function name:"), QLineEdit::Normal, name, &ok);
+    QInputDialog inputDialog(this->mainWindow);
+    inputDialog.resize(500, 100);
```
Comment (XVilka) [inline src/menus/DisassemblyContextMenu.cpp:814]: @wargio here
