### PR TITLE
Fix crash on multiple Widget destructors (#3516)

### LINKED ISSUE #3516: cutter crashes silently at closing + freezing
**Environment information**
* Operating System: fedora 42, kde plasma 6.4.5, kde frameworks 6.18, Qt 6.9.2, kernel 6.16.9-200
* Cutter version:  2.4.0-dev-0b16482
* Rizin 0.9.0 & rz-ghidra 1.0
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: 

**Describe the bug**

    A) save your project and close the application. it closes with a crash...
    B) when the project is saved, systematically for a few moments, cutter freezes and generates a crash

**To Reproduce**

    use cutter & close it

**Expected behavior**

 be able to close cutter without freezes and crashes

**Screenshots**

the [cutter-backtrace.txt](https://github.com/user-attachments/files/22697413/cutter_backtrace.txt)

screenrecord:
https://github.com/user-attachments/assets/1105b85a-6aeb-4cd4-9e08-34901f29178a

**Additional context**
 builded with the flags (-D_FORTIFY_SOURCE=2 -fstack-protector-strong -fPIE -Wformat)

### PR DESCRIPTION
**Pull request by marmitar**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [X] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)
- [ ] I've used AI tools to generate fully or partially these code changes and I'm sure the changes are not copyrighted by somebody else.

**Detailed description**

Noticed that `importAddresses` was being used after being freed (see my logs on #3516) and I was able to fix it by moving that property to `FunctionModel` instead of `FunctionsWidget`, but I also found a lot of other widgets were causing similar crashes. I think this should cover most if not all of them.

What this does specifically is attach the lifetime of the widget data to each Model instead the widget itself, so they can still be used after the widget has been deallocated. This is similar to what is already implemented on some widgets ([Breakpoint](https://github.com/rizinorg/cutter/blob/dev/src/widgets/BreakpointWidget.h), [Relocs](https://github.com/rizinorg/cutter/blob/dev/src/widgets/RelocsWidget.h), [Stack](https://github.com/rizinorg/cutter/blob/dev/src/widgets/StackWidget.h) and [Threads](https://github.com/rizinorg/cutter/blob/dev/src/widgets/ThreadsWidget.h)).

Also found a similar pattern on `BaseFindResultsDialog`, although I didn't get a crash from it specifically.

Apparently, only required for Qt 6.9.1+.

**Test plan (required)**

While Cutter is running, there should be no difference at all. Only at shutdown that there shouldn't be any more crashes coming from the Widgets. It is also reported in #3516 that the crash can happen while saving, but I didn't get that error specifically. I'll see if I can reproduce it.

I haven't tested Qt5 yet (edit: 5.15.5 works). It would be nice to verify that it works there too.

**Closing issues**

Closes #3516

### CODE REVIEW

**Comment by marmitar** [comment]
I tested the AppImages from the artifacts and they seem to be working fine, but they are also using older versions of Qt, so the fix may not be necessary.

**Comment by wargio** [comment]
it could be some weird bug in QT

**Comment by marmitar** [comment]
I couldn't find any clear indication in the Qt docs of the lifetime rules for this case, but I think it has always been intended for the Model to own the data. See [Designing a model (Qt 5.5)](https://doc.qt.io/archives/qt-5.5/model-view-programming.html#a-read-only-example-model), it has an example with `QStringList` and data is owned there.

So probably should have always been like this, but recent versions (between Qt 6.7.3 and 6.10.1) are doing something different during destruction.

**Comment by marmitar** [comment]
I've updated the code to avoid a copy with `BaseFindResultsModel`'s constructor.

**Review by wargio — COMMENTED** [review]
can you open an executable (at least ~1mb of size) and check the memory footprint of before and after these changes?

**Comment by marmitar** [comment]
Okay, I compiled 546ff769 and 6bbd137f using the same flags as [Arch Linux](https://gitlab.archlinux.org/archlinux/packaging/packages/rz-cutter/-/blob/main/PKGBUILD) (system libs, Qt 6.10.1) and ran tests on [mkcert](https://github.com/FiloSottile/mkcert/releases/tag/v1.4.4), trying to do the same on both versions.

I'll leave them open here and I can run specific tests if you want.

## Dev branch

### Long run (802 MiB)

```console
$ /usr/bin/time -f "Time: %E (%Uuser + %Ssys) | RAM: %M kB | CPU: %P" ./cutter-546ff769 ~/Downloads/mkcert-v1.4.4-linux-amd64
[...]
Command terminated by signal 11
Time: 46:28.31 (16414.05user + 3.83sys) | RAM: 821572 kB | CPU: 588%
```

### Short run (544 MiB)

```log
Time: 1:14.21 (8.42user + 0.49sys) | RAM: 557308 kB | CPU: 12%
```

## This branch

### Long run (831 MiB)

```console
$ /usr/bin/time -f "Time: %E (%Uuser + %Ssys) | RAM: %M kB | CPU: %P" ./cutter-6bbd137f ~/Downloads/mkcert-v1.4.4-linux-amd64
[...]
Time: 46:19.66 (16480.07user + 8.46sys) | RAM: 851188 kB | CPU: 593%
```

### Short run (545 MiB)

```log
Time: 1:12.91 (7.92user + 0.50sys) | RAM: 558076 kB | CPU: 11%
```

**Review by wargio — APPROVED** [review]
Nice! the difference is nothing.

LGTM! @notxvilka @karliss have a look as this resolves some issues

**Review by notxvilka — COMMENTED** [review]
The idea is sound and  code looks correct. But I am not familiar with Qt quirks to judge if this is an appropriate fix.

**Comment by marmitar** [comment]
I'm no expert on Qt either, but on most widgets, the data is only accessed by the parent between `beginResetModel()` and `endResetModel()`, so these ones should be safe. Looking at the code again, the ones that don't follow this pattern and probably need a more careful review are:

- `BaseFindResultsDialog`
- `FlagsWidget`
- `FlirtWidget`
- `SearchModel`
- `TypesModel`

Edit: although even those do a read-only access. Additionally, Qt should only remove the children (the model here) after the parent dies, unless it's deleted manually. Since the model is only managed automatically, lifetime shouldn't be an issue in this case.

File: src/tools/basefind/BaseFindResultsDialog.cpp [hunk 1]
```diff
@@ -7,14 +7,14 @@
 #include <core/Cutter.h>
 #include <CutterApplication.h>
 
-BaseFindResultsModel::BaseFindResultsModel(QList<BasefindResultDescription> *list, QObject *parent)
+BaseFindResultsModel::BaseFindResultsModel(QList<BasefindResultDescription> &&list, QObject *parent)
     : QAbstractListModel(parent), list(list)
```
Comment (karliss) [inline src/tools/basefind/BaseFindResultsDialog.cpp:11]: If I am not mistaken you need to move the list here as well otherwise passing argument as rvalue reference won't do what you want. Small demonstration here https://godbolt.org/z/zf5MTzEMr

Although Qt containers like QList implement implicit sharing/copy on write behavior.  See https://doc.qt.io/qt-6/implicit-sharing.html . So there is less need to avoiding "copy" compared to STL containers.

Comment (marmitar) [reply src/tools/basefind/BaseFindResultsDialog.cpp:11]: Oh, indeed. These implicit copies on C++ always get me. Well, I'll rollback to 4192cb5 and let Qt take (edit: care) of it then.

**Review by karliss — APPROVED** [review]
Overall seems reasonable.

I am glad to see that there was finally a reason to refactor all the backwards models.

A portion of them that used .UI files and thus had `std::unique_ptr<actual gui> ui;` probably were fine. As UI would have been destroyed before the lists representing data.  Ones that created all the GUI in code or had a base classes might have had more problematic destruction order (which after introduction of addressable item widgets might have been a large portion). 
Still having a model point to data within widget is kind of backwards so it was good too refactor. Not completely perfect as some widgets are poking at the various internal fields of model more than they should, but let's leave that refactoring for another time.

As a side note, the fact that QT is querying model as result of UI update during destruction is kind of wrong. There is no point recalculating layout for child widgets which are about to be deleted. Not necessary harmful, but it's wasteful.  Ideally QT shouldn't do that, which Is I assume why it wasn't a problem before.

**Comment by marmitar** [comment]
So maybe there is indeed a Qt issue here. Based on the logs, the UI update was caused by [change 637377](https://codereview.qt-project.org/c/qt/qtbase/+/637377) and later (partially?) fixed by [change 645955](https://codereview.qt-project.org/c/qt/qtbase/+/645955), but maybe not fully. Both changes also entered Qt 6.8, but after 6.8.3, so that would explain why only 6.9.1 had issues.

Edit: Yeah, the fix is only for `QEvent::Hide = 18`, but what's causing recalculation here is `QEvent::StyleChange = 100`.

```log
(gdb) f 20
#20 0x00007f8d9f96a99d in QCoreApplication::sendEvent (receiver=<optimized out>, event=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1549
1549	   return notifyInternal2(receiver, event);
(gdb) f 19
#19 0x00007f8d9f96a958 in QCoreApplication::notifyInternal2 (receiver=0x556be2b87220, event=0x7ffc8f7034a0) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1109
1109	   return qApp->notify(receiver, event);
(gdb) p event
$5 = (QEvent *) 0x7ffc8f7034a0
(gdb) p event->type()
❌️ Cannot evaluate function -- may be inlined
(gdb) p event->t
$6 = 100
```

**Review by notxvilka — APPROVED** [review]

**Comment by notxvilka** [comment]
The redness is unrelated - it's because of the rizin API changes

**Comment by marmitar** [comment]
Hi, just an update on this. I opened [QTBUG-143119](https://qt-project.atlassian.net/browse/QTBUG-143119) for the unnecessary `QEvent::StyleChange`. That is now fixed in dev and should be included in Qt 6.11.
