### PR TITLE
JSDec as cutter native plugin

### LINKED ISSUE #3303: Failed to parse JSON (jsdec)
Opened `calc.exe` with the build from 
and immediately got an error from `jsdec`, even without opening the corresponding tab:

image

```
[x] Use -AA or aaaa to perform additional experimental analysis.
{"code":"/* jsdec pseudo code output */\n/* C:\\Windows\\System32\\calc.exe @ 0x140001870 */\n#include <stdint.h>\n \nint64_t entry0 (void) {\nlabel_1:\n    rax = rsp;\n    *((rax + 8)) = rbx;\n    *((rax + 0x10)) = rsi;\n    *((rax + 0x18)) = rdi;\n    *((rax + 0x20)) = r14;\n    r14d = 0;\n    *(var_98h) = r14d;\n    rcx = rax - 0x78;\n    GetStartupInfoW (r15);\n    rax = *(gs:0x30);\n    rbx = *((rax + 8));\n    esi = r14d;\n    do {\n        eax = 0;\n        __asm (\"lock cmpxchg qword [api-ms-win-core-processthreads-l1-1-0.dll_GetStartupInfoW], rbx\");\n        if (? == ?) {\n            goto label_2;\n        }\n        if (rax == rbx) {\n            ebx = 1;\n            esi = 1;\n            goto label_3;\n        }\n        ecx = api-ms-win-core-processthreads-l1-1-0.dll_GetStartupInfoW;\n        Sleep ();\n    } while (1);\nlabel_2:\n    ebx = 1;\nlabel_3:\n    eax = *(data.140003628);\n    if (eax == ebx) {\n        edi = 0x1f;\n        ecx = 0x1f;\n        _amsg_exit ();\n        goto label_4;\n    }\n    eax = *(data.140003628);\n    if (eax != 0) {\n        goto label_5;\n    }\n    *(data.140003628) = ebx;\n    r15 = data_1400022a8;\n    rdi = data_140002290;\n    *(var_88h) = rdi;\n    eax = r14d;\n    *(var_94h) = eax;\n    do {\n        if (rdi >= r15) {\n            goto label_6;\n        }\n        if (eax != 0) {\n            goto label_7;\n        }\n        if (*(rdi) != r14) {\n            rax = *(rdi);\n            rcx = *(data.140002270);\n            eax = void (*rcx)() ();\n            *(var_94h) = eax;\n        }\n        rdi += 8;\n        *(var_88h) = rdi;\n    } while (1);\nlabel_6:\n    if (eax != 0) {\nlabel_7:\n        eax = 0xff;\n        goto label_8;\nlabel_5:\n        *(data.1400035d4) = ebx;\n    }\n    edi = 0x1f;\nlabel_4:\n    eax = *(data.140003628);\n    if (eax == ebx) {\n        rdx = data_140002288;\n        rcx = data_140002278;\n        _initterm ();\n        *(data.140003628) = 2;\n    }\n    if (esi == 0) {\n        rax = r14;\n        tmp_0 = 0x140003620;\n        0x140003620 = rax;\n        rax = tmp_0;\n    }\n    if (*(data.140003630) != r14) {\n        eax = flirt_IsNonwritableInCurrentImage (data.140003630);\n        if (eax == 0) {\n            goto label_9;\n        }\n        r8d = 0;\n        edx = r8 + 2;\n        ecx = 0;\n        rax = *(data.140003630);\n        r9 = *(data.140002270);\n        void (*r9)() ();\n    }\nlabel_9:\n    rax = imp._wcmdln;\n    rcx = *(rax);\n    if (rcx == 0) {\n        eax = 0xff;\n        goto label_8;\n    }\n    *(var_90h) = rcx;\n    edx = *(var_98h);\nlabel_0:\n    eax = *(rcx);\n    if (ax > 0x20) {\n        goto label_10;\n    }\n    if (ax == 0) {\n        goto label_11;\n    }\n    if (edx != 0) {\n        goto label_10;\n    }\n    do {\nlabel_11:\n        ax -= bx;\n        if (ax > di) {\n            goto label_12;\n        }\n        rcx += 2;\n        *(var_90h) = rcx;\n        eax = *(rcx);\n    } while (1);\nlabel_12:\n    eax = *(var_38h);\n    r9d = 0xa;\n    if ((*(var_3ch) & bl) != 0) {\n        r9d = eax;\n    }\n    r8 = rcx;\n    edx = 0;\n    rcx = data_140000000;\n    eax = fcn_14000113c ();\n    *(data.1400035d0) = eax;\n    if (*(data.1400035f0) == r14d) {\n        ecx = eax;\n        exit ();\n    }\n    if (*(data.1400035d4) == r14d) {\n        cexit ();\n        eax = *(data.1400035d0);\n    }\n    goto label_8;\nlabel_10:\n    if (ax == 0x22) {\n        eax = r14d;\n        al = (edx == 0) ? 1 : 0;\n        edx = eax;\n        *(var_98h) = eax;\n    }\n    rcx += 2;\n    *(var_90h) = rcx;\n    goto label_0;\nlabel_8:\n    r11 = var_8h;\n    rbx = *((r11 + 0x10));\n    rsi = *((r11 + 0x18));\n    rdi = *((r11 + 0x20));\n    r14 = *((r11 + 0x28));\n    return rax;\n    flirt_security_init_cookie ();\n    goto label_1;\n}\n","annotations":[{"start":0,"end":30,"type":"offset","offset":"5368714752"},{"start":0,"end":30,"type":"syntax_highlight","syntax_highlight":"comment"},{"start":31,"end":79,"type":"offset","offset":"5368714752"},{"start":31,"end":79,"type":"syntax_highlight","syntax_highlight":"comment"},{"start":80,"end":99,"type":"offset","offset":"5368714752"},{"start":80,"end":99,"type":"syntax_highlight","syntax_highlight":"comment"},{"start":100,"end":101,"type":"offset","offset":"5368714752"},{"start":102,"end":125,"type":"offset","offset":"5368714752"},{"start":102,"end":109,"type":"syntax_highlight","syntax_highlight":"datatype"},{"start":110,"end":116,"type":"syntax_highlight","syntax_highlight":"function_name"},{"start":110,"end":116,"type":"function_name","name":"entry0","offset":"5368715376"},{"start":118,"end":122,"type":"syntax_highlight","syntax_highlight":"datatype"},{"start":126,"end":134,"type":"offset","offset":"5368714752"},{"start":135,"end":149,"type":"offset","offset":"5368714752"},{"start":150,"end":173,"type":"offset","offset":"5368714755"},{"start":163,"end":164,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":163,"end":164,"type":"constant_variable","offset":"8"},{"start":174,"end":200,"type":"offset","offset":"5368714759"},{"start":187,"end":191,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":187,"end":191,"type":"constant_variable","offset":"16"},{"start":201,"end":227,"type":"offset","offset":"5368714763"},{"start":214,"end":218,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":214,"end":218,"type":"constant_variable","offset":"24"},{"start":228,"end":254,"type":"offset","offset":"5368714767"},{"start":241,"end":245,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":241,"end":245,"type":"constant_variable","offset":"32"},{"start":255,"end":268,"type":"offset","offset":"5368714780"},{"start":266,"end":267,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":266,"end":267,"type":"constant_variable","offset":"0"},{"start":269,"end":291,"type":"offset","offset":"5368714783"},{"start":292,"end":313,"type":"offset","offset":"5368714788"},{"start":308,"end":312,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":308,"end":312,"type":"constant_variable","offset":"120"},{"start":314,"end":340,"type":"offset","offset":"5368714792"},{"start":341,"end":362,"type":"offset","offset":"5368714799"},{"start":356,"end":360,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":356,"end":360,"type":"constant_variable","offset":"48"},{"start":363,"end":386,"type":"offset","offset":"5368714808"},{"start":382,"end":383,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":382,"end":383,"type":"constant_variable","offset":"8"},{"start":387,"end":402,"type":"offset","offset":"5368714812"},{"start":403,"end":411,"type":"offset","offset":"5368714815"},{"start":407,"end":409,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":412,"end":428,"type":"offset","offset":"5368714815"},{"start":426,"end":427,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":426,"end":427,"type":"constant_variable","offset":"0"},{"start":429,"end":531,"type":"offset","offset":"5368714817"},{"start":437,"end":442,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":444,"end":529,"type":"syntax_highlight","syntax_highlight":"global_variable"},{"start":532,"end":553,"type":"offset","offset":"5368714826"},{"start":540,"end":542,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":554,"end":579,"type":"offset","offset":"5368714826"},{"start":580,"end":589,"type":"offset","offset":"5368714826"},{"start":590,"end":615,"type":"offset","offset":"5368714831"},{"start":598,"end":600,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":616,"end":636,"type":"offset","offset":"5368714833"},{"start":634,"end":635,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":634,"end":635,"type":"constant_variable","offset":"1"},{"start":637,"end":657,"type":"offset","offset":"5368714838"},{"start":655,"end":656,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":655,"end":656,"type":"constant_variable","offset":"1"},{"start":658,"end":683,"type":"offset","offset":"5368714840"},{"start":684,"end":693,"type":"offset","offset":"5368714840"},{"start":694,"end":766,"type":"offset","offset":"5368714842"},{"start":740,"end":741,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":740,"end":741,"type":"constant_variable","offset":"1"},{"start":744,"end":745,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":744,"end":745,"type":"constant_variable","offset":"0"},{"start":767,"end":784,"type":"offset","offset":"5368714847"},{"start":785,"end":801,"type":"offset","offset":"5368714853"},{"start":791,"end":796,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":798,"end":799,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":798,"end":799,"type":"constant_variable","offset":"1"},{"start":802,"end":810,"type":"offset","offset":"5368714855"},{"start":811,"end":823,"type":"offset","offset":"5368714855"},{"start":821,"end":822,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":821,"end":822,"type":"constant_variable","offset":"1"},{"start":824,"end":832,"type":"offset","offset":"5368714860"},{"start":833,"end":861,"type":"offset","offset":"5368714860"},{"start":850,"end":859,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":850,"end":859,"type":"constant_variable","offset":"140003628"},{"start":862,"end":883,"type":"offset","offset":"5368714868"},{"start":866,"end":868,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":884,"end":903,"type":"offset","offset":"5368714870"},{"start":898,"end":902,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":898,"end":902,"type":"constant_variable","offset":"31"},{"start":904,"end":923,"type":"offset","offset":"5368714875"},{"start":918,"end":922,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":918,"end":922,"type":"constant_variable","offset":"31"},{"start":924,"end":946,"type":"offset","offset":"5368714877"},{"start":932,"end":942,"type":"syntax_highlight","syntax_highlight":"function_name"},{"start":932,"end":942,"type":"function_name","name":"sub.msvcrt.dll__amsg_exit","offset":"5368715683"},{"start":947,"end":968,"type":"offset","offset":"5368714882"},{"start":969,"end":974,"type":"offset","offset":"5368714882"},{"start":975,"end":1003,"type":"offset","offset":"5368714884"},{"start":992,"end":1001,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":992,"end":1001,"type":"constant_variable","offset":"140003628"},{"start":1004,"end":1023,"type":"offset","offset":"5368714892"},{"start":1008,"end":1010,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":1019,"end":1020,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":1019,"end":1020,"type":"constant_variable","offset":"0"},{"start":1024,"end":1045,"type":"offset","offset":"5368714892"},{"start":1046,"end":1051,"type":"offset","offset":"5368714892"},{"start":1052,"end":1080,"type":"offset","offset":"5368714894"},{"start":1063,"end":1072,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":1063,"end":1072,"type":"constant_variable","offset":"140003628"},{"start":1081,"end":1106,"type":"offset","offset":"5368714900"},{"start":1107,"end":1132,"type":"offset","offset":"5368714907"},{"start":1133,"end":1154,"type":"offset","offset":"5368714914"},{"start":1155,"end":1170,"type":"offset","offset":"5368714919"},{"start":1171,"end":1192,"type":"offset","offset":"5368714922"},{"start":1193,"end":1201,"type":"offset","offset":"5368714926"},{"start":1197,"end":1199,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":1202,"end":1227,"type":"offset","offset":"5368714929"},{"start":1210,"end":1212,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":1228,"end":1253,"type":"offset","offset":"5368714929"},{"start":1254,"end":1263,"type":"offset","offset":"5368714929"},{"start":1264,"end":1287,"type":"offset","offset":"5368714933"},{"start":1272,"end":1274,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":1283,"end":1284,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":1283,"end":1284,"type":"constant_variable","offset":"0"},{"start":1288,"end":1313,"type":"offset","offset":"5368714933"},{"start":1314,"end":1323,"type":"offset","offset":"5368714933"},{"start":1324,"end":1352,"type":"offset","offset":"5368714938"},{"start":1332,"end":1334,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":1353,"end":1378,"type":"offset","offset":"5368714940"},{"start":1379,"end":1415,"type":"offset","offset":"5368714943"},{"start":1404,"end":1413,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":1404,"end":1413,"type":"constant_variable","offset":"140002270"},{"start":1416,"end":1451,"type":"offset","offset":"5368714950"},{"start":1434,"end":1438,"type":"syntax_highlight","syntax_highlight":"datatype"},{"start":1452,"end":1481,"type":"offset","offset":"5368714952"},{"start":1482,"end":1491,"type":"offset","offset":"5368714952"},{"start":1492,"end":1509,"type":"offset","offset":"5368714956"},{"start":1507,"end":1508,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":1507,"end":1508,"type":"constant_variable","offset":"8"},{"start":1510,"end":1535,"type":"offset","offset":"5368714960"},{"start":1536,"end":1552,"type":"offset","offset":"5368714965"},{"start":1542,"end":1547,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":1549,"end":1550,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":1549,"end":1550,"type":"constant_variable","offset":"1"},{"start":1553,"end":1561,"type":"offset","offset":"5368714967"},{"start":1562,"end":1581,"type":"offset","offset":"5368714969"},{"start":1566,"end":1568,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":1577,"end":1578,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":1577,"end":1578,"type":"constant_variable","offset":"0"},{"start":1582,"end":1590,"type":"offset","offset":"5368714971"},{"start":1591,"end":1610,"type":"offset","offset":"5368714971"},{"start":1605,"end":1609,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":1605,"end":1609,"type":"constant_variable","offset":"255"},{"start":1611,"end":1632,"type":"offset","offset":"5368714976"},{"start":1633,"end":1641,"type":"offset","offset":"5368714981"},{"start":1642,"end":1674,"type":"offset","offset":"5368714981"},{"start":1675,"end":1680,"type":"offset","offset":"5368714981"},{"start":1681,"end":1696,"type":"offset","offset":"5368714987"},{"start":1691,"end":1695,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":1691,"end":1695,"type":"constant_variable","offset":"31"},{"start":1697,"end":1705,"type":"offset","offset":"5368714992"},{"start":1706,"end":1734,"type":"offset","offset":"5368714992"},{"start":1723,"end":1732,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":1723,"end":1732,"type":"constant_variable","offset":"140003628"},{"start":1735,"end":1756,"type":"offset","offset":"5368715000"},{"start":1739,"end":1741,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":1757,"end":1786,"type":"offset","offset":"5368715002"},{"start":1787,"end":1816,"type":"offset","offset":"5368715009"},{"start":1817,"end":1838,"type":"offset","offset":"5368715016"},{"start":1825,"end":1834,"type":"syntax_highlight","syntax_highlight":"function_name"},{"start":1825,"end":1834,"type":"function_name","name":"sub.msvcrt.dll__initterm","offset":"5368715939"},{"start":1839,"end":1869,"type":"offset","offset":"5368715021"},{"start":1854,"end":1863,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":1854,"end":1863,"type":"constant_variable","offset":"140003628"},{"start":1861,"end":1862,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":1861,"end":1862,"type":"constant_variable","offset":"2"},{"start":1870,"end":1875,"type":"offset","offset":"5368715021"},{"start":1876,"end":1895,"type":"offset","offset":"5368715033"},{"start":1880,"end":1882,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":1891,"end":1892,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":1891,"end":1892,"type":"constant_variable","offset":"0"},{"start":1896,"end":1914,"type":"offset","offset":"5368715035"},{"start":1915,"end":1943,"type":"offset","offset":"5368715038"},{"start":1931,"end":1942,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":1931,"end":1942,"type":"constant_variable","offset":"5368722976"},{"start":1944,"end":1970,"type":"offset","offset":"5368715038"},{"start":1952,"end":1963,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":1952,"end":1963,"type":"constant_variable","offset":"5368722976"},{"start":1971,"end":1991,"type":"offset","offset":"5368715038"},{"start":1992,"end":1997,"type":"offset","offset":"5368715038"},{"start":1998,"end":2033,"type":"offset","offset":"5368715052"},{"start":2002,"end":2004,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":2013,"end":2022,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2013,"end":2022,"type":"constant_variable","offset":"140003630"},{"start":2034,"end":2099,"type":"offset","offset":"5368715061"},{"start":2048,"end":2081,"type":"syntax_highlight","syntax_highlight":"function_name"},{"start":2048,"end":2081,"type":"function_name","name":"flirt.IsNonwritableInCurrentImage","offset":"5368715792"},{"start":2088,"end":2097,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2088,"end":2097,"type":"constant_variable","offset":"140003630"},{"start":2100,"end":2123,"type":"offset","offset":"5368715068"},{"start":2108,"end":2110,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":2119,"end":2120,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2119,"end":2120,"type":"constant_variable","offset":"0"},{"start":2124,"end":2149,"type":"offset","offset":"5368715068"},{"start":2150,"end":2159,"type":"offset","offset":"5368715068"},{"start":2160,"end":2176,"type":"offset","offset":"5368715070"},{"start":2174,"end":2175,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2174,"end":2175,"type":"constant_variable","offset":"0"},{"start":2177,"end":2198,"type":"offset","offset":"5368715073"},{"start":2196,"end":2197,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2196,"end":2197,"type":"constant_variable","offset":"2"},{"start":2199,"end":2215,"type":"offset","offset":"5368715077"},{"start":2213,"end":2214,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2213,"end":2214,"type":"constant_variable","offset":"0"},{"start":2216,"end":2248,"type":"offset","offset":"5368715079"},{"start":2237,"end":2246,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2237,"end":2246,"type":"constant_variable","offset":"140003630"},{"start":2249,"end":2280,"type":"offset","offset":"5368715086"},{"start":2269,"end":2278,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2269,"end":2278,"type":"constant_variable","offset":"140002270"},{"start":2281,"end":2305,"type":"offset","offset":"5368715093"},{"start":2289,"end":2293,"type":"syntax_highlight","syntax_highlight":"datatype"},{"start":2306,"end":2311,"type":"offset","offset":"5368715093"},{"start":2312,"end":2320,"type":"offset","offset":"5368715096"},{"start":2321,"end":2343,"type":"offset","offset":"5368715096"},{"start":2344,"end":2361,"type":"offset","offset":"5368715103"},{"start":2362,"end":2381,"type":"offset","offset":"5368715109"},{"start":2366,"end":2368,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":2377,"end":2378,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2377,"end":2378,"type":"constant_variable","offset":"0"},{"start":2382,"end":2401,"type":"offset","offset":"5368715111"},{"start":2396,"end":2400,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2396,"end":2400,"type":"constant_variable","offset":"255"},{"start":2402,"end":2423,"type":"offset","offset":"5368715116"},{"start":2424,"end":2429,"type":"offset","offset":"5368715116"},{"start":2430,"end":2451,"type":"offset","offset":"5368715121"},{"start":2452,"end":2473,"type":"offset","offset":"5368715126"},{"start":2474,"end":2482,"type":"offset","offset":"5368715130"},{"start":2483,"end":2500,"type":"offset","offset":"5368715130"},{"start":2501,"end":2521,"type":"offset","offset":"5368715137"},{"start":2505,"end":2507,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":2514,"end":2518,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2514,"end":2518,"type":"constant_variable","offset":"32"},{"start":2522,"end":2544,"type":"offset","offset":"5368715137"},{"start":2545,"end":2550,"type":"offset","offset":"5368715137"},{"start":2551,"end":2569,"type":"offset","offset":"5368715142"},{"start":2555,"end":2557,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":2565,"end":2566,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2565,"end":2566,"type":"constant_variable","offset":"0"},{"start":2570,"end":2592,"type":"offset","offset":"5368715142"},{"start":2593,"end":2598,"type":"offset","offset":"5368715142"},{"start":2599,"end":2618,"type":"offset","offset":"5368715146"},{"start":2603,"end":2605,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":2614,"end":2615,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2614,"end":2615,"type":"constant_variable","offset":"0"},{"start":2619,"end":2641,"type":"offset","offset":"5368715146"},{"start":2642,"end":2647,"type":"offset","offset":"5368715146"},{"start":2648,"end":2656,"type":"offset","offset":"5368715148"},{"start":2652,"end":2654,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":2657,"end":2666,"type":"offset","offset":"5368715148"},{"start":2667,"end":2684,"type":"offset","offset":"5368715148"},{"start":2685,"end":2707,"type":"offset","offset":"5368715154"},{"start":2693,"end":2695,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":2708,"end":2734,"type":"offset","offset":"5368715154"},{"start":2735,"end":2744,"type":"offset","offset":"5368715154"},{"start":2745,"end":2762,"type":"offset","offset":"5368715156"},{"start":2760,"end":2761,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2760,"end":2761,"type":"constant_variable","offset":"2"},{"start":2763,"end":2788,"type":"offset","offset":"5368715160"},{"start":2789,"end":2810,"type":"offset","offset":"5368715165"},{"start":2811,"end":2827,"type":"offset","offset":"5368715168"},{"start":2817,"end":2822,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":2824,"end":2825,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2824,"end":2825,"type":"constant_variable","offset":"1"},{"start":2828,"end":2837,"type":"offset","offset":"5368715170"},{"start":2838,"end":2859,"type":"offset","offset":"5368715174"},{"start":2860,"end":2874,"type":"offset","offset":"5368715182"},{"start":2870,"end":2873,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2870,"end":2873,"type":"constant_variable","offset":"10"},{"start":2875,"end":2908,"type":"offset","offset":"5368715188"},{"start":2879,"end":2881,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":2904,"end":2905,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2904,"end":2905,"type":"constant_variable","offset":"0"},{"start":2909,"end":2927,"type":"offset","offset":"5368715188"},{"start":2928,"end":2933,"type":"offset","offset":"5368715188"},{"start":2934,"end":2947,"type":"offset","offset":"5368715192"},{"start":2948,"end":2960,"type":"offset","offset":"5368715195"},{"start":2958,"end":2959,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":2958,"end":2959,"type":"constant_variable","offset":"0"},{"start":2961,"end":2986,"type":"offset","offset":"5368715197"},{"start":2987,"end":3014,"type":"offset","offset":"5368715204"},{"start":2997,"end":3010,"type":"syntax_highlight","syntax_highlight":"function_name"},{"start":2997,"end":3010,"type":"function_name","name":"fcn.14000113c","offset":"5368713532"},{"start":3015,"end":3043,"type":"offset","offset":"5368715209"},{"start":3044,"end":3080,"type":"offset","offset":"5368715222"},{"start":3048,"end":3050,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":3081,"end":3099,"type":"offset","offset":"5368715224"},{"start":3100,"end":3116,"type":"offset","offset":"5368715226"},{"start":3117,"end":3122,"type":"offset","offset":"5368715226"},{"start":3123,"end":3159,"type":"offset","offset":"5368715239"},{"start":3127,"end":3129,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":3160,"end":3177,"type":"offset","offset":"5368715241"},{"start":3178,"end":3210,"type":"offset","offset":"5368715247"},{"start":3211,"end":3216,"type":"offset","offset":"5368715247"},{"start":3217,"end":3234,"type":"offset","offset":"5368715253"},{"start":3235,"end":3244,"type":"offset","offset":"5368715255"},{"start":3245,"end":3266,"type":"offset","offset":"5368715259"},{"start":3249,"end":3251,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":3259,"end":3263,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":3259,"end":3263,"type":"constant_variable","offset":"34"},{"start":3267,"end":3286,"type":"offset","offset":"5368715261"},{"start":3287,"end":3319,"type":"offset","offset":"5368715266"},{"start":3308,"end":3309,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":3308,"end":3309,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":3308,"end":3309,"type":"constant_variable","offset":"0"},{"start":3308,"end":3309,"type":"constant_variable","offset":"0"},{"start":3313,"end":3314,"type":"constant_variable","offset":"1"},{"start":3313,"end":3314,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":3320,"end":3338,"type":"offset","offset":"5368715269"},{"start":3339,"end":3364,"type":"offset","offset":"5368715271"},{"start":3365,"end":3370,"type":"offset","offset":"5368715271"},{"start":3371,"end":3384,"type":"offset","offset":"5368715275"},{"start":3382,"end":3383,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":3382,"end":3383,"type":"constant_variable","offset":"2"},{"start":3385,"end":3406,"type":"offset","offset":"5368715279"},{"start":3407,"end":3424,"type":"offset","offset":"5368715284"},{"start":3425,"end":3433,"type":"offset","offset":"5368715334"},{"start":3434,"end":3451,"type":"offset","offset":"5368715334"},{"start":3452,"end":3478,"type":"offset","offset":"5368715342"},{"start":3471,"end":3475,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":3471,"end":3475,"type":"constant_variable","offset":"16"},{"start":3479,"end":3505,"type":"offset","offset":"5368715346"},{"start":3498,"end":3502,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":3498,"end":3502,"type":"constant_variable","offset":"24"},{"start":3506,"end":3532,"type":"offset","offset":"5368715350"},{"start":3525,"end":3529,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":3525,"end":3529,"type":"constant_variable","offset":"32"},{"start":3533,"end":3559,"type":"offset","offset":"5368715354"},{"start":3552,"end":3556,"type":"syntax_highlight","syntax_highlight":"constant_variable"},{"start":3552,"end":3556,"type":"constant_variable","offset":"40"},{"start":3560,"end":3575,"type":"offset","offset":"5368715363"},{"start":3564,"end":3570,"type":"syntax_highlight","syntax_highlight":"keyword"},{"start":3576,"end":3610,"type":"offset","offset":"5368715380"},{"start":3580,"end":3606,"type":"syntax_highlight","syntax_highlight":"function_name"},{"start":3580,"end":3606,"type":"function_name","name":"flirt.security_init_cookie","offset":"5368713892"},{"start":3611,"end":3628,"type":"offset","offset":"5368715389"},{"start":3629,"end":3630,"type":"offset","offset":"5368715389"}]}
Failed to parse JSON
```

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Builds jsdec as a cutter native plugin.

Fix #3303

### CODE REVIEW

**Comment by XVilka** [comment]
Didn't completely help:
image

File: src/core/Cutter.cpp [hunk 1]
```diff
@@ -286,6 +287,7 @@ void CutterCore::loadDefaultCutterRC()
     }
     qInfo() << tr("Loading initialization file from ") << cutterRCFilePath;
     rz_core_cmd_file(core, cutterRCFilePath.toUtf8().constData());
+    rz_cons_flush();
 }
 
 QList<QString> CutterCore::sdbList(QString path)
```
Comment (XVilka) [inline src/core/Cutter.cpp:293]: We should remove this function in the future.

**Review by XVilka — APPROVED** [review]

File: src/core/Cutter.cpp (hunk 1 above)
Comment (wargio) [reply src/core/Cutter.cpp:293]: there are many thing that should be rewritten in cutter to simplify stuff.
