### PR TITLE
Solved the bug of missing NX and PIC bits in Dashboard.

### LINKED ISSUE #2895: NX bit and PIC missing from Dashboard
**Environment information**
* Operating System: Linux kali 5.15.0-kali2-amd64 1 SMP Debian 5.15.5-2kali2 (2021-12-22) x86_64 GNU/Linux (Kali 2021.4)
* Cutter version: Cutter v2.0.5-x64.Linux (AppImage)
* Obtained from:
  - [ ] Built from source
  - [X] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: ELF 64-bit LSB executable

**Describe the bug**

The latest version of Cutter fails to detect a given binary's protection. Cutter does not seem to be able to detect whether NX bit and PIC protections are present. 

**To Reproduce**

1. Open a binary (ELF, in my case) file with Cutter.
2. Go to `Dashboard`.
3. See missing protections.

**Expected behavior**

In previous versions of Cutter all the information was displayed correctly. The latest version always states N/A.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by bassuniz**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

This PR solves the problem of missing NX bit and PIC protections. The solution is to use rizin API directly.
Implementation:
1 - Remove using `setBool(this->ui->nxEdit, item, "nx");` and `setBool(this->ui->nxEdit, item, "pic");` 
2- Using the API directly by calling `RzBinInfo *binInfo = rz_bin_get_info(core->bin);` as this function returns a struct containing the correct values of NX bit and PIC bit: `has_nx` and `has_pi`
3 - calling the function `setNxPIC` that sets the linedit with the correct values:
```
void Dashboard::setNxPIC(RzBinInfo *binInfo)
{
    //setting text
    int nx = binInfo->has_nx;
    int pic = binInfo->has_pi;
    setPlainText(ui->nxEdit, tr(intToText(nx)));
    setPlainText(ui->picEdit, tr(intToText(pic)));
}
```
**This solution follows the trend of using the API directly inside the cutter #2666. This solution can be generalized to all the boolean values inside the dashboard**

**Test plan (required)**

1- open new file using cutter 
2- check the values of NX bit and PIC bit
3- you can confirm the correctness of the values using the command `$ rz-bin -I filename` or using `$ checksec --file=filename`

**Closing issues**

closes #2895

### CODE REVIEW

**Review by wargio — CHANGES_REQUESTED** [review]
I do not think this is the right way to fix this. i would try to understand why the nx, pic fields are not in the json object here used.

File: src/widgets/Dashboard.cpp [hunk 1]
```diff
@@ -238,3 +248,35 @@ void Dashboard::setBool(QLineEdit *textBox, const CutterJson &jsonObject, const
...
+char* Dashboard::intToText(int value){
+    if (value){
+        return "True";
+    }
+    else if (!value){
+        return "False";
+    }
+    else{
+        return "N/A";
+    }
```
Comment (wargio) [inline src/widgets/Dashboard.cpp]: side note: this is dead code since it is impossible to reach this section. 
to enter the `if (value) {` the number has to be non-zero and for `else if (!value) {` it has to be zero, therefore you cover all the possible numbers for `int` type.

**Comment by bassuniz** [comment]
> I do not think this is the right way to fix this. i would try to understand why the nx, pic fields are not in the json object here used.

I tried to trace the error causing the bug but failed. so I presented this as an alternative solution for using the API directly. Here the function `rz_bin_get_info` returns a struct with the desired values. therefore, I accessed the values from this struct directly. I didn't need JSON to parse the values as I can use them directly.

File: src/widgets/Dashboard.cpp (hunk 1 above)
Comment (bassuniz) [reply src/widgets/Dashboard.cpp]: Yes. Thank you for pointing this out. I just wanted to test the output quickly but forgot to change it.

**Comment by wargio** [comment]
let me give you a different option, since we want to remove these hacks to get values from rizin and since you indeed have decided to use the best solution for this issue, i suggest then to convert all the values there to use the rizin C api so you can fix 2 issues with one PR.

**Comment by bassuniz** [comment]
> let me give you a different option, since we want to remove these hacks to get values from rizin and since you indeed have decided to use the best solution for this issue, i suggest then to convert all the values there to use the rizin C api so you can fix 2 issues with one PR.

Great, I will look into that.

File: src/widgets/Dashboard.cpp [hunk 2]
```diff
@@ -21,6 +21,7 @@
 #include <QDialog>
 #include <QTreeWidget>
 
+
```
Comment (XVilka) [inline src/widgets/Dashboard.cpp]: Unnecessary change

**Review by XVilka — CHANGES_REQUESTED** [review]
Agree with @wargio - it's better to get all data using the API, not just those values.

**Comment by bassuniz** [comment]
> Agree with @wargio - it's better to get all data using the API, not just those values.

great I will do that.

File: src/widgets/Dashboard.cpp [hunk 3]
```diff
@@ -65,20 +65,29 @@ void Dashboard::updateContents()
...
-    setBool(this->ui->canaryEdit, item2, "canary");
-    setBool(this->ui->cryptoEdit, item2, "crypto");
-    setBool(this->ui->nxEdit, item2, "nx");
-    setBool(this->ui->picEdit, item2, "pic");
+    //remove to use API directly
+//    setBool(this->ui->vaEdit, item2, "va");
+//    setBool(this->ui->canaryEdit, item2, "canary");
+//    setBool(this->ui->cryptoEdit, item2, "crypto");
+//    setBool(this->ui->nxEdit, item, "nx");
+//    setBool(this->ui->picEdit, item, "pic");
```
Comment (wargio) [inline src/widgets/Dashboard.cpp]:
```suggestion
```

File: src/widgets/Dashboard.cpp [hunk 4]
```diff
@@ -64,21 +64,29 @@ void Dashboard::updateContents()
...
-    setBool(this->ui->strippedEdit, item2, "stripped");
-    setBool(this->ui->relocsEdit, item2, "relocs");
-
     // Add file hashes, analysis info and libraries
     RzCoreLocked core(Core());
+
+    // using API directly to get boolean values in dashboard
+    RzBinInfo *binInfo = rz_bin_get_info(core->bin);
+
+    //setting boolean values
```
Comment (XVilka) [inline src/widgets/Dashboard.cpp]: Please don't forget space between `//` and comment

File: src/widgets/Dashboard.cpp [hunk 5]
```diff
@@ -64,21 +64,29 @@ void Dashboard::updateContents()
...
+    //setting the value of relocs and stripped
+    bool relocs_value = RZ_BIN_DBG_RELOCS & binInfo->dbg_info;
+    bool stripped_value = RZ_BIN_DBG_STRIPPED & binInfo->dbg_info;
+    setPlainText(this->ui->strippedEdit, intToText(stripped_value));
+    setPlainText(this->ui->relocsEdit, intToText(relocs_value));
+
     RzBinFile *bf = rz_bin_cur(core->bin);
     RzList *hashes = rz_bin_file_compute_hashes(core->bin, bf, UT64_MAX);
 
+
```
Comment (XVilka) [inline src/widgets/Dashboard.cpp]: Unnecessary change

**Review by XVilka — CHANGES_REQUESTED** [review]
Now it's the right approach.

File: src/widgets/Dashboard.cpp [hunk 6]
```diff
@@ -62,21 +47,40 @@ void Dashboard::updateContents()
...
     RzBinFile *bf = rz_bin_cur(core->bin);
+    RzBinInfo *binInfo = rz_bin_get_info(core->bin);
+
+    // Setting text values from the API
+    setPlainText(this->ui->fileEdit,binInfo->file);
+    setPlainText(this->ui->formatEdit,binInfo->rclass);
+    setPlainText(this->ui->typeEdit,binInfo->type);
+    setPlainText(this->ui->archEdit,binInfo->arch);
+    setPlainText(this->ui->langEdit, binInfo->lang);
+    setPlainText(this->ui->classEdit,binInfo->bclass);
```
Comment (XVilka) [inline src/widgets/Dashboard.cpp]: Please be consistent with formatting and put space after comma.

File: src/widgets/Dashboard.cpp [hunk 7]
```diff
@@ -62,21 +47,40 @@ void Dashboard::updateContents()
...
-    setBool(this->ui->nxEdit, item2, "nx");
-    setBool(this->ui->picEdit, item2, "pic");
-    setBool(this->ui->staticEdit, item2, "static");
-    setBool(this->ui->strippedEdit, item2, "stripped");
-    setBool(this->ui->relocsEdit, item2, "relocs");
-
     // Add file hashes, analysis info and libraries
     RzCoreLocked core(Core());
+
+    // Using API directly to get values in dashboard
```
Comment (XVilka) [inline src/widgets/Dashboard.cpp]: Unnecessary comment

File: src/widgets/Dashboard.cpp [hunk 8]
```diff
@@ -62,21 +47,40 @@ void Dashboard::updateContents()
...
     RzBinFile *bf = rz_bin_cur(core->bin);
+    RzBinInfo *binInfo = rz_bin_get_info(core->bin);
+
+    // Setting text values from the API
```
Comment (XVilka) [inline src/widgets/Dashboard.cpp]: Unnecessary comment.

File: src/widgets/Dashboard.cpp [hunk 9]
```diff
@@ -238,3 +242,44 @@ void Dashboard::setBool(QLineEdit *textBox, const CutterJson &jsonObject, const
         setPlainText(textBox, tr("N/A"));
     }
 }
+
+/**
+ * @brief Setting boolean values text according to parsed value from API
+ * @param RzBinInfo
+ */
+
```
Comment (XVilka) [inline src/widgets/Dashboard.cpp]: Unnecessary empty line

File: src/widgets/Dashboard.cpp [hunk 10]
```diff
@@ -238,3 +242,44 @@ void Dashboard::setBool(QLineEdit *textBox, const CutterJson &jsonObject, const
         setPlainText(textBox, tr("N/A"));
     }
 }
+
+/**
+ * @brief Setting boolean values text according to parsed value from API
```
Comment (XVilka) [inline src/widgets/Dashboard.cpp]: Too generic description, it's only for the binary information.

File: src/widgets/Dashboard.cpp [hunk 11]
```diff
@@ -238,3 +242,44 @@ void Dashboard::setBool(QLineEdit *textBox, const CutterJson &jsonObject, const
...
+    setPlainText(this->ui->strippedEdit,QVariant(stripped_value).toString());
+    setPlainText(this->ui->relocsEdit,QVariant(relocs_value).toString());
+}
+
+/**
+ * @brief Set the text of a QLineEdit as True, False according to the integer value
+ * @param integer value
+ */
+
+char* Dashboard::intToText(int value){
```
Comment (XVilka) [inline src/widgets/Dashboard.cpp]: Can be removed.

File: src/widgets/Dashboard.cpp [hunk 12]
```diff
@@ -238,3 +242,44 @@ void Dashboard::setBool(QLineEdit *textBox, const CutterJson &jsonObject, const
...
+    setPlainText(ui->vaEdit, tr(intToText(va)));
+    setPlainText(ui->canaryEdit, tr(intToText(canary)));
+    setPlainText(ui->cryptoEdit, tr(intToText(crypto)));
+    setPlainText(ui->nxEdit, tr(intToText(nx)));
+    setPlainText(ui->picEdit, tr(intToText(pic)));
+
+    // Setting the value of "relocs" and "stripped"
+    bool relocs_value = RZ_BIN_DBG_RELOCS & binInfo->dbg_info;
+    bool stripped_value = RZ_BIN_DBG_STRIPPED & binInfo->dbg_info;
+    setPlainText(this->ui->strippedEdit,QVariant(stripped_value).toString());
```
Comment (XVilka) [inline src/widgets/Dashboard.cpp]: Also formatting.

**Review by XVilka — CHANGES_REQUESTED** [review]

File: src/widgets/Dashboard.cpp [hunk 13]
```diff
@@ -238,3 +239,38 @@ void Dashboard::setBool(QLineEdit *textBox, const CutterJson &jsonObject, const
...
+    setPlainText(this->ui->relocsEdit, setBoolText(relocs_value));
+}
+
+/**
+ * @brief Set the text of a QLineEdit as True, False
+ * @param boolean value
+ */
+const char *Dashboard::setBoolText(bool value)
+{
+    return value ? "True" : "False";
```
Comment (XVilka) [inline src/widgets/Dashboard.cpp:247]: Have you tried to use QVariant here?

File: src/widgets/Dashboard.h [hunk 14]
```diff
@@ -34,6 +34,8 @@ private slots:
     std::unique_ptr<Ui::Dashboard> ui;
     void setPlainText(QLineEdit *textBox, const QString &text);
     void setBool(QLineEdit *textBox, const CutterJson &jsonObject, const char *key);
+    void setBoolvalues(RzBinInfo *binInfo);
```
Comment (XVilka) [inline src/widgets/Dashboard.h]: To be consistent with other names it should be `setBoolValues()`. But the name is bad and too generic. It should be something indicating that it works only with the `RzBinInfo`, something like `setRzBinInfo()` or similar.

**Review by XVilka — CHANGES_REQUESTED** [review]

File: src/widgets/Dashboard.cpp (hunk 13 above)
Comment (bassuniz) [reply src/widgets/Dashboard.cpp:247]: Yes, but it returned "true" or "false" with lower case letters. I thought it should be uppercase.

**Review by XVilka — APPROVED** [review]

**Review by thestr4ng3r — APPROVED** [review]
