### PR TITLE
Switch to widget on seek change

### LINKED ISSUE #1839: Chnage to disassembly\hexdump widget when seek to non-functions in Graph widget
**Describe the bug**

Currently, when we double click on an address on Graph widget, Cutter will seek to this address in Graph. This is meaningless when the new address is not part of a function. And then the user will see this message:
image

I suggest the following behavior when seeking in graph:

1. If the address is a (part of) function, seek to it in Graph widget
2. If the address is CODE but not part of a function, seek to it in Disassembly Widget
3. If the address is Data (e.g string), seek to it in hexdump widget

Make sure not to open new widget when not necessary and if you do, make sure it will be opened in the same dock.

**To Reproduce**

1. Open graph widget
2. Find a reference to an address which isn't part of a function (e.g `lea rdi, <string>` , `push <string>`, `call [reloc.smthing]`)
3. See that the address opened in Graph widget and you get an empty graph

### PR DESCRIPTION
**Pull request by tsogp**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)
- [ ] I've used AI tools to generate fully or partially these code changes and I'm sure the changes are not copyrighted by somebody else.

**Detailed description**

Automatically switches to the most appropriate widget (Graph, Disassembly, or Hexdump) based on the target address's content type. This prevents the "empty graph" issue in the Graph view.

Seek to a CODE section:
[Screencast_20260331_001002.webm](https://github.com/user-attachments/assets/26cb67cf-0756-409d-8380-9f1b6950f50f)

Seek to a DATA section:
[Screencast_20260331_001148.webm](https://github.com/user-attachments/assets/4edde086-4f39-4a20-b5c3-dbb299d1fe2a)

**Test plan (required)**

- Open Cutter with any binary and open a Graph widget
- Seek to a function, verify that the Graph widget is focused or opened.
- Seek to a string or a data variable, verify that the Hexdump widget is opened/raised.
- Seek to an address in an executable section that is not part of a function, verify that the Disassembly widget is opened/raised.
- Navigate between a function and a string, then click the Back and Forward buttons in the toolbar, verify that the active widget switches automatically between Graph and Hexdump.

**Closing issues**
closes #1839

### CODE REVIEW

**Comment by tsogp** [comment]
@notxvilka @wargio @PremadeS Guys, when you have some time, may I kindly ask you to review this PR?

**Review by wargio — APPROVED** [review]
Nice improvement

**Review by PremadeS — CHANGES_REQUESTED** [review]
In disassembly widget double clicking on an address that is inside a function, switches to graph. If double clicked in disassembly then it should stay in disassembly IMO, same with graph

Similar to above, When in disassembly double clicking on any data reference shows hexdump (should stay in disassembly) - after landing in hexdump using the undo seek switches to graph when it should switch to disassembly

**Comment by tsogp** [comment]
> In disassembly widget double clicking on an address that is inside a function, switches to graph. If double clicked in disassembly then it should stay in disassembly IMO, same with graph

[@PremadeS](https://github.com/PremadeS) Hi! So I shouldn't switch views between disassembly and graph views? Only disassembly <-> hexdump, graph <-> hexdump, right?

> Similar to above, When in disassembly double clicking on any data reference shows hexdump (should stay in disassembly) - after landing in hexdump using the undo seek switches to graph when it should switch to disassembly

Will fix

**Comment by PremadeS** [comment]
> Hi! So I shouldn't switch views between disassembly and graph views? Only disassembly <-> hexdump, graph <-> hexdump, right?

Ideally, 
* if the user is currently at disassembly widget then clicking on anything should stay in disassembly widget
* If the user is currently at graph widget then the following should happen:
    - If the address is a (part of) function, seek to it in Graph widget
    - If the address is CODE but not part of a function, seek to it in Disassembly Widget
    - If the address is Data (e.g string), seek to it in hexdump widget

In short functionality for disassembly widget should remain the same, changes should only be made for graph

**Comment by tsogp** [comment]
@PremadeS Done! Now we can't switch to others widgets while clicking on the addresses in anywhere other than Graph widget. I have also enabled global widget switch history, so that the user can switch to the widget where they have done some seeking with Undo and Redo functions. 

https://github.com/user-attachments/assets/04b2d7af-51e8-4fa4-8500-9e588c18a680

**Comment by PremadeS** [comment]
Switches to the other disassembly widget when adding a new one and clicking anywhere
Steps to reproduce:
Add a second disassembly widget
1- Window->Add Disassembly
2- Try clicking anywhere in this new disassembly widget, it will switch to the previous one each time

> In short functionality for disassembly widget should remain the same, changes should only be made for graph

I would suggest only doing this and leaving the global widget switch history for now
Saving memory widgets in history seems like a task that can easily become complex, better to leave that for a separate PR IMO

**Review by PremadeS — CHANGES_REQUESTED** [review]
^

**Comment by tsogp** [comment]
@PremadeS I have removed the history saving for now. Right now it doesn't switch to any other widgets if it's not a Graph widget. In the history too, it will just seek onto the previous address but stay on the current widget.

**Comment by tsogp** [comment]
https://github.com/user-attachments/assets/67ef8d2d-b98a-416f-bcde-db0e7f9e6207

File: src/core/Cutter.cpp [hunk 1]
```diff
@@ -1150,6 +1150,30 @@ void CutterCore::setConfig(const char *k, const QString &v)
...
+        if (addr >= sect.vaddr && addr < sect.vaddr + sect.vsize) {
+            if (sect.perm.toLower().contains('x')) {
+                return AddressTypeHint::Code;
+            }
+            if (sect.perm.toLower().contains('r') || sect.perm.toLower().contains('w')) {
+                return AddressTypeHint::Data;
+            }
+            return AddressTypeHint::Unknown;
+        }
+    }
```
Comment (PremadeS) [inline src/core/Cutter.cpp]: Better to create a new function that will return the section at given address. It should use `rz_bin_get_section_at`  to get the section through rizin

File: src/core/MainWindow.cpp [hunk 2]
```diff
@@ -1627,6 +1670,11 @@ void MainWindow::on_actionForward_triggered()
     core->seekNext();
 }
 
+void MainWindow::on_core_seekChanged(RVA addr, CutterCore::SeekHistoryType type)
+{
+    this->showAddress(addr);
+}
```
Comment (PremadeS) [inline src/core/MainWindow.cpp]: Could you explain the use of this?
Removing this doesn't affect anything or maybe I missed something?

Comment (PremadeS) [reply src/core/MainWindow.cpp]: Also gives this warning:

`qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_core_seekChanged(RVA,CutterCore::SeekHistoryType)`

File: src/core/MainWindow.cpp [hunk 3]
```diff
@@ -1020,6 +1022,27 @@ void MainWindow::showMemoryWidget(MemoryWidgetType type)
...
+                    memoryWidget->getSeekable()->seek(address);
+                }
+                return memoryWidget;
+            }
+        }
+    }
+
+    if (address == RVA_INVALID) {
+        address = Core()->getOffset();
+    }
```
Comment (PremadeS) [inline src/core/MainWindow.cpp]: Shouldn't this be at the start of the function? before iterating through all of the dock widgets

**Review by PremadeS — CHANGES_REQUESTED** [review]
Logic wise it's working fine

File: src/core/Cutter.cpp (hunk 1 above)
Comment (tsogp) [reply src/core/Cutter.cpp]: Done, it's `Cutter::getSectionAtAddress(RVA address)`

File: src/core/MainWindow.cpp (hunk 2 above)
Comment (tsogp) [reply src/core/MainWindow.cpp]: This used to be necessary when I tried to do widget switch history, but now it no longer is, so I have removed it.

File: src/core/MainWindow.cpp (hunk 3 above)
Comment (tsogp) [reply src/core/MainWindow.cpp]: Yes, it should, I moved it to the beginning, thank you very much

**Comment by tsogp** [comment]
@PremadeS Thank you very much for the feedback! I've addressed it, can you please have a look?

File: src/core/Cutter.cpp [hunk 4]
```diff
@@ -1150,6 +1150,32 @@ void CutterCore::setConfig(const char *k, const QString &v)
...
+    if (functionIn(addr)) {
+        return AddressTypeHint::Function;
+    }
+
+    auto section = getSectionAtAddress(addr);
+    if (section.name.isEmpty()) {
+        return AddressTypeHint::Unknown;
+    }
+
+    if (addr >= section.vaddr && addr < section.vaddr + section.vsize) {
```
Comment (PremadeS) [inline src/core/Cutter.cpp]: No need for this check now

File: src/core/Cutter.cpp [hunk 5]
```diff
@@ -1150,6 +1150,32 @@ void CutterCore::setConfig(const char *k, const QString &v)
...
+        if (section.perm.toLower().contains('x')) {
```
Comment (PremadeS) [inline src/core/Cutter.cpp]:
```suggestion
        if (section.perm.contains('x', Qt::CaseInsensitive)) {
```

File: src/core/Cutter.cpp [hunk 6]
```diff
@@ -1150,6 +1150,32 @@ void CutterCore::setConfig(const char *k, const QString &v)
...
+            return AddressTypeHint::Code;
+        }
+        if (section.perm.toLower().contains('r') || section.perm.toLower().contains('w')) {
+            return AddressTypeHint::Data;
+        }
```
Comment (PremadeS) [inline src/core/Cutter.cpp]:
```suggestion
        if (section.perm.contains('r', Qt::CaseInsensitive)
            || section.perm.contains('w', Qt::CaseInsensitive)) {
            return AddressTypeHint::Data;
        }
```

**Review by PremadeS — CHANGES_REQUESTED** [review]
Almost there, hopefully last set of changes

**Comment by tsogp** [comment]
@PremadeS Done

**Review by PremadeS — APPROVED** [review]

**Review by notxvilka — APPROVED** [review]

**Comment by notxvilka** [comment]
For now blocked on the Rizin and other components updates: https://github.com/rizinorg/cutter/pull/3600

**Comment by PremadeS** [comment]
@tsogp Could you please update branch?

**Comment by tsogp** [comment]
@PremadeS Done!
