### PR TITLE
Fix arrow line calculation when disasm line is has multiple newlines.

### LINKED ISSUE #2615: Jump arrow starting and ending at wrong address in assembly view
**Environment information**
* Operating System: linuxmint 20.1
* Cutter version: 1.12.0
* File format: elf64
 * Arch: x86
 * Type: EXEC (Executable file)

**Describe the bug**
The jump arrow is starting at / pointing to the wrong address due to the data structure.

**To Reproduce**
1. Open shellcode below
2. Right click at `0x05`, Set as..., Data..., *..., item size: 128, number of items: 1
3. See error

**Expected behavior**
The jump arrow should start on / end at the correct address.

**Screenshots**
image

**Shellcode**
```
e98500000090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090eb0e9090909090909090909090909090
```

### LINKED ISSUE #3141: [Hexagon] Jump target arrows are incorrect
**Environment information**
* Operating System: Debian-11
* Cutter version: 2.2.0
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: ELF

**Describe the bug**

The arrows pointing to jump targets are incorrect. In the screenshots you can see that the arrow originating correctly from address `0x551c` in Rizin, starts incorrectly from address `0x5518` in Cutter.
The same problem happens with the addresses the arrow is pointing to.

**To Reproduce**

1. Open a Hexagon binary with Cutter like `rizin-testbins/elf/analysis/hexagon-hello-loop`
2. Go to `0x5500` or any other offset in the binary
3. Compare the arrows to Rizin
4. See mismatch

**Expected behavior**

The arrows pointing to the same offset as in Rizin.

**Screenshots**

Rizin

rz-1

Cutter
rz-2

**Additional context**

The bug possibly comes from the way the jump targets for Hexagon instructions are set.

Hexagon has very long instruction words. Those instruction words are commonly referred to as packets. Each packet can contain multiple instructions. Each packet has a single PC address associated to it. This PC address is always equal to the start of the packet (the first instruction in the packet).

PC-relative jump targets are always relative to the packet address. If a packet is not completely disassembled (the first instruction is unknown) the packet address is not known. Hence the jump target is incorrectly calculated from the wrong address.

The bug likely originates from this behavior. The arrows are possibly drawn when the packet is still not disassembled completely. Because of that the jump targets are calculated relative to the wrong address (not the first one in the packet). Due to that the arrows point to an incorrect jump target.

Contrary to Rizin, Cutter might not update it's GUI after each user interaction. So the incorrect arrows remain.

I haven't done any debugging, but it seems the most likely reason for this bug to me.

Relevant chapters in the [Hexagon programmers reference manual v67](https://developer.qualcomm.com/qfile/67417/80-n2040-45_b_qualcomm_hexagon_v67_programmer_reference_manual.pdf):
- Ch. 3.3.2 - Sequence semantics (Intro into packets + the PC of a packet is equal to the start of a packet)
- Ch. 8.3 - Software Branches (general info about branches).

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

Fix #2615
Fix #3141

**Detailed description**

Before:
image

Now:
image

Also images from the branch on the other bins related to this issue:
image
image

### CODE REVIEW

File: src/core/Cutter.cpp [hunk 1]
```diff
@@ -4143,11 +4143,20 @@ QList<DisassemblyLine> CutterCore::disassembleLines(RVA offset, int lines)
...
     QList<DisassemblyLine> r;
     for (const auto &t : CutterPVector<RzAnalysisDisasmText>(vec.get())) {
-        DisassemblyLine line;
-        line.offset = t->offset;
-        line.text = ansiEscapeToHtml(t->text);
-        line.arrow = t->arrow;
-        r << line;
+        QString text = t->text;
+        QStringList tokens = text.split('\n');
+        // text might contains multiple lines
```
Comment (XVilka) [inline src/core/Cutter.cpp]: "might contain"

**Review by XVilka — APPROVED** [review]
LGTM aside typo
