### PR TITLE
Don't use @a: for listing cpus.

### LINKED ISSUE #2304: Opening files
**Environment information**
* Operating System: Windows 10 version 2004
* Cutter version: 1.10.3
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded from release
  - [ ] Distribution repository
* File format: aarch64

**Describe the bug**
When opening files Cutter only analyses correctly about 5% of the time. I'll select a file to open, choose Auto-Analysis, and keep all options at default except Architecture and CPU which I set to arm and v8. Sometimes it works and a long list of functions is displayed. But the vast majority of the time I just see the screenshot below.

**To Reproduce**

1. Open a file choosing arm as the architecture and v8 as the processor. I managed to replicate this with a bunch of different files, like [this](https://github.com/radareorg/cutter/files/4947834/SecureROM-s5l8960xsi-1704.10-RELEASE.txt) file.
2. Cutter analyses correctly or it doesn't.

**Expected behavior**

Cutter would open and analyse the file correctly, as it does sometimes.

**Screenshots**

image

**Additional context**

While trying to take a screenshot of the failed opening, the file actually opened the first time. But then the next time it failed. And then it worked again. And then failed several times. I can't find any consistent behavior, it seems entirely random.

### PR DESCRIPTION
**Pull request by karliss**
For some architectures like 8051 doing `@a:` has sideeffects.

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

* In the initial options change arch to 8051
* Change arch to arm
* Open a file, make sure there are no errors during opening, file opens and the bytes can bee seen
* Test that cpu listing works, Try selecting a few different cpus in the initial dialog, make sure cpu list gets filled with expected values.

**Closing issues**
Closes #2304

### CODE REVIEW

**Review by ITAYC0HEN — APPROVED** [review]
Good catch with this one. Can't believe you guys actually find this edge case, great

Should we have a follow-up task to have a better solution and fix the issue on r2?

File: src/dialogs/InitialOptionsDialog.cpp [hunk 1]
```diff
@@ -103,15 +103,23 @@ void InitialOptionsDialog::updateCPUComboBox()
...
+    QStringList cpus;
+    if (!arch.isEmpty()) {
+        auto pluginDescr = std::find_if(asmPlugins.begin(), asmPlugins.end(), [&](const RAsmPluginDescription &plugin) {
+            return plugin.name == arch;
+        });
+        if (pluginDescr != asmPlugins.end()) {
+#if QT_VERSION >= QT_VERSION_CHECK(5,14,0)
+            cpus = pluginDescr->cpus.split(",", Qt::SkipEmptyParts);
+#else
+            cpus = pluginDescr->cpus.split(",", Qt::SkipEmptyParts);
```
Comment (xarkes) [inline src/dialogs/InitialOptionsDialog.cpp:116]: Am I tired or this line is the same as 114? (which means the `#if` is useless?)

Comment (xarkes) [reply src/dialogs/InitialOptionsDialog.cpp:116]: Yeah ok just noticed this is the line failing the build on Ubuntu 16.04...

Comment (karliss) [reply src/dialogs/InitialOptionsDialog.cpp]: Looks like It was me who was tired. It's good that we have CI to double check.
