### PR TITLE
Get rid of stale jump arrows in disassembly widget.

### LINKED ISSUE #3114: Old jump arrow does not disappear after changing jump address
**Environment information**
* Operating System: Windows 10
* Cutter version: 2.1.2
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: pe

**Describe the bug**
After changing the jump address in a "jump" command, a new arrow appears, pointing to a new address, but the old one does not disappear, so both arrows are present on the disassembly panel. If you change the address again, three arrows will come from this command and so on.
"Refresh Contents" button does not remove the old arrow, switching between panels also does not help. The old arrow disappears when the disassembly panel is reopened.

**To Reproduce**

1. Change the jump address of any "jump" command.

**Expected behavior**
The old jump arrow should disappear.

**Screenshots**
Before change:
image

After change:
image

### PR DESCRIPTION
**Pull request by beauby**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

This commit forces the jump arrows to be recomputed upon `paintEvent`, thus avoiding to draw stale arrows (e.g. after a jump instruction was edited).

**Test plan (required)**

Cf. #3114

**Closing issues**

closes #3114

### CODE REVIEW

**Comment by beauby** [comment]
Might also close #2854

**Comment by karliss** [comment]
If I remember correctly. Not clearing the list was intentional to better support following cases:

* You look at the start of arrow and select the corresponding assembly line. Arrow gets hilighted. You start scrolling down to see the other end. The hilighted line will remain visible as long as it intersects current view even when both ends are invisible. 

* Keeping the arrows visible while they are still in screen also has the benefit of minimizing the arrow reordering which makes it easier to visually keep track of what goes where. It's hard to track arrows if their order keeps changing. 


A better solution while keeping the two cases above would be to only wipe the arrows after actions that might modify the assembly. Doesn't have to be exact. It's fine if there are some false positives and it removes lines after modification which didn't change the jumps, for example replacing some mov with nop. But scrolling up and down shouldn't remove them, beside the existing code which removes arrows that go outside the screen.

**Comment by beauby** [comment]
@karliss Thanks for the context. I updated the PR to only clear the arrow starting at that offset when an instruction is edited.

**Review by XVilka — APPROVED** [review]

File: src/widgets/DisassemblyWidget.cpp [hunk 1]
```diff
@@ -990,3 +996,9 @@ void DisassemblyLeftPanel::paintEvent(QPaintEvent *event)
 
     lastBeginOffset = lines.first().offset;
 }
+
+void DisassemblyLeftPanel::clearArrowFrom(RVA offset)
+{
+    std::remove_if(std::begin(arrows), std::end(arrows),
```
Comment (karliss) [inline src/widgets/DisassemblyWidget.cpp]: That's not how `std::remove_if` should be used. `std::remove` group of functions are made to work with any iterator it doesn't actually know anything about `std::vector` or other container so it can't actually erase the elements. It only reorders them and returns an iterator pointing to the start of range that you need to remove using `std::vector` API.

https://en.cppreference.com/w/cpp/algorithm/remove see the docs for more information.

**Review by karliss — CHANGES_REQUESTED** [review]

File: src/widgets/DisassemblyWidget.cpp (hunk 1 above)
Comment (beauby) [reply src/widgets/DisassemblyWidget.cpp]: Thanks, this is now fixed.

**Review by wargio — APPROVED** [review]
I have tested the patch. it works correctly (at least on linux)
